dashboard frontend
gdsc-nits-org/tecnoesis-2024 pull request #18
Opened 2024-10-09 12:56 UTC by velgardey

2024-10-09 15:11 UTC, JDeepD requested changes

2024-10-09 15:11 UTC, JDeepD commented on src/app/dashboard/page.tsx
> +          <svg
Replace.

2024-10-09 15:11 UTC, JDeepD commented on src/app/dashboard/page.tsx
> +          <Button variant="ghost" className="text-white bg-blue-900/70 hover:bg-blue-800/80 rounded-full px-1 sm:px-2 md:px-3 lg:px-4 py-1 sm:py-1.5 md:py-2 text-xs sm:text-sm md:text-base lg:text-lg
FIx for mobile.

2024-10-09 15:11 UTC, JDeepD commented on src/app/dashboard/page.tsx
> +        console.error("Error fetching dashboard data:", error);
`toast.error("")`

2024-10-09 15:11 UTC, JDeepD commented on src/components/ui/button.tsx
> +import * as React from "react"
Remove shadcn.

2024-10-09 15:11 UTC, JDeepD commented on src/components/ui/card.tsx
> +import * as React from "react"
Remove

2024-10-10 17:03 UTC, JDeepD commented
@velgardey run `pnpm build` before pushing. Also, delete `pnpm-lockfile` and run `pnpm i` again. then push.

2024-10-10 17:55 UTC, velgardey commented
![Screenshot 2024-10-10 232037](https://github.com/user-attachments/assets/a0261543-b055-4a31-83a3-a5b5ed7ced50)

@JDeepD The pages are properly being built locally

2024-10-12 04:02 UTC, JDeepD commented
@velgardey Delete the `pnpm-lockfile` and do `pnpm i`. Push to see if build is fixed. Also, resolve the merge conflicts

2024-10-13 08:17 UTC, merged